/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminRealisationsIndexRouteImport } from './routes/admin/realisations/index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminAiMemoryIndexRouteImport } from './routes/admin/ai-memory/index'
import { Route as AdminRealisationsNewRouteImport } from './routes/admin/realisations/new'
import { Route as AdminRealisationsIdRouteImport } from './routes/admin/realisations/$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin/articles/$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRealisationsIndexRoute = AdminRealisationsIndexRouteImport.update({
  id: '/admin/realisations/',
  path: '/admin/realisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiMemoryIndexRoute = AdminAiMemoryIndexRouteImport.update({
  id: '/admin/ai-memory/',
  path: '/admin/ai-memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRealisationsNewRoute = AdminRealisationsNewRouteImport.update({
  id: '/admin/realisations/new',
  path: '/admin/realisations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRealisationsIdRoute = AdminRealisationsIdRouteImport.update({
  id: '/admin/realisations/$id',
  path: '/admin/realisations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/admin/articles/new',
  path: '/admin/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/admin/articles/$id',
  path: '/admin/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cgu': typeof CguRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminLayoutRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/work/': typeof WorkIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/realisations/$id': typeof AdminRealisationsIdRoute
  '/admin/realisations/new': typeof AdminRealisationsNewRoute
  '/admin/ai-memory/': typeof AdminAiMemoryIndexRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/realisations/': typeof AdminRealisationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cgu': typeof CguRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/journal': typeof JournalIndexRoute
  '/work': typeof WorkIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/realisations/$id': typeof AdminRealisationsIdRoute
  '/admin/realisations/new': typeof AdminRealisationsNewRoute
  '/admin/ai-memory': typeof AdminAiMemoryIndexRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/realisations': typeof AdminRealisationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cgu': typeof CguRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/services': typeof ServicesRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/work/': typeof WorkIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/realisations/$id': typeof AdminRealisationsIdRoute
  '/admin/realisations/new': typeof AdminRealisationsNewRoute
  '/admin/ai-memory/': typeof AdminAiMemoryIndexRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/realisations/': typeof AdminRealisationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cgu'
    | '/contact'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/services'
    | '/admin'
    | '/api/chat'
    | '/auth/login'
    | '/journal/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/journal/'
    | '/work/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/realisations/$id'
    | '/admin/realisations/new'
    | '/admin/ai-memory/'
    | '/admin/articles/'
    | '/admin/realisations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cgu'
    | '/contact'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/services'
    | '/admin'
    | '/api/chat'
    | '/auth/login'
    | '/journal/$slug'
    | '/work/$slug'
    | '/journal'
    | '/work'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/realisations/$id'
    | '/admin/realisations/new'
    | '/admin/ai-memory'
    | '/admin/articles'
    | '/admin/realisations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cgu'
    | '/contact'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/services'
    | '/admin/_layout'
    | '/api/chat'
    | '/auth/login'
    | '/journal/$slug'
    | '/work/$slug'
    | '/admin/'
    | '/journal/'
    | '/work/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/realisations/$id'
    | '/admin/realisations/new'
    | '/admin/ai-memory/'
    | '/admin/articles/'
    | '/admin/realisations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CguRoute: typeof CguRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ServicesRoute: typeof ServicesRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthLoginRoute: typeof AuthLoginRoute
  JournalSlugRoute: typeof JournalSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminRealisationsIdRoute: typeof AdminRealisationsIdRoute
  AdminRealisationsNewRoute: typeof AdminRealisationsNewRoute
  AdminAiMemoryIndexRoute: typeof AdminAiMemoryIndexRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminRealisationsIndexRoute: typeof AdminRealisationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/realisations/': {
      id: '/admin/realisations/'
      path: '/admin/realisations'
      fullPath: '/admin/realisations/'
      preLoaderRoute: typeof AdminRealisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-memory/': {
      id: '/admin/ai-memory/'
      path: '/admin/ai-memory'
      fullPath: '/admin/ai-memory/'
      preLoaderRoute: typeof AdminAiMemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/realisations/new': {
      id: '/admin/realisations/new'
      path: '/admin/realisations/new'
      fullPath: '/admin/realisations/new'
      preLoaderRoute: typeof AdminRealisationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/realisations/$id': {
      id: '/admin/realisations/$id'
      path: '/admin/realisations/$id'
      fullPath: '/admin/realisations/$id'
      preLoaderRoute: typeof AdminRealisationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/admin/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/admin/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CguRoute: CguRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  ServicesRoute: ServicesRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  ApiChatRoute: ApiChatRoute,
  AuthLoginRoute: AuthLoginRoute,
  JournalSlugRoute: JournalSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminRealisationsIdRoute: AdminRealisationsIdRoute,
  AdminRealisationsNewRoute: AdminRealisationsNewRoute,
  AdminAiMemoryIndexRoute: AdminAiMemoryIndexRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminRealisationsIndexRoute: AdminRealisationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
